-- MySQL Script generated by MySQL Workbench
-- Wed Jun 20 21:02:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbloja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbloja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbloja` DEFAULT CHARACTER SET utf8 ;
USE `dbloja` ;

-- -----------------------------------------------------
-- Table `dbloja`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbloja`.`treino` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aluno` VARCHAR(45) NOT NULL,
  `treinoA` VARCHAR(45) NOT NULL,
  `treinoB` VARCHAR(45) NOT NULL,
  `treinoC` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbloja`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbloja`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `treino_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_treino_idx` (`treino_id` ASC),
  CONSTRAINT `fk_usuario_treino`
    FOREIGN KEY (`treino_id`)
    REFERENCES `dbloja`.`treino` (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from usuario;
select * from treino;

insert into usuario(nome,sobrenome,telefone,cpf,endereco,tipo,email,senha) values ('admin','admin','45-44444-4444','222.222.222.22','Rua','2','admin@gmail.com', 'admin');